# This is a config for E2B sandbox template.
# You can use template ID (fgtixr1xv52jfx2b4l97) or template name (capsule-next-developer) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("capsule-next-developer") # Sync sandbox
# sandbox = await AsyncSandbox.create("capsule-next-developer") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('capsule-next-developer')

team_id = "58da4ae7-1293-4506-8558-d0198f159f13"
dockerfile = "e2b.Dockerfile"
template_name = "capsule-next-developer"
template_id = "fgtixr1xv52jfx2b4l97"
