# This is a config for E2B sandbox template.
# You can use template ID (v9z5gy4t7t6ca08gop8o) or template name (capsule-nextjs-developer) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("capsule-nextjs-developer") # Sync sandbox
# sandbox = await AsyncSandbox.create("capsule-nextjs-developer") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('capsule-nextjs-developer')

team_id = "58da4ae7-1293-4506-8558-d0198f159f13"
dockerfile = "e2b.Dockerfile"
template_name = "capsule-nextjs-developer"
template_id = "v9z5gy4t7t6ca08gop8o"
